[features]
resolution = true
skip-lint = false

[programs.localnet]
yield_adapter_dispatcher = "37fdMFG3eh91i7WYk4MgwYBGqoXK4dbpV73UUh6uxvtY"
reference_yield_adapter = "BCvRj9JakpU1mpo67yt7WjknSAcTqAJMWCSyurcRhBb1"

[programs.devnet]
yield_adapter_dispatcher = "37fdMFG3eh91i7WYk4MgwYBGqoXK4dbpV73UUh6uxvtY"
reference_yield_adapter = "BCvRj9JakpU1mpo67yt7WjknSAcTqAJMWCSyurcRhBb1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm test"
