[package]
name = "reference_yield_adapter"
version = "0.1.0"
description = "Reference adapter implementation for the Solana Yield Adapter Standard."
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "reference_yield_adapter"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
default = []

[dependencies]
anchor-lang = { workspace = true, features = ["init-if-needed"] }
anchor-spl = { workspace = true }
blake3 = { workspace = true }
hashbrown = { workspace = true }
proc-macro-crate = { workspace = true }

[dev-dependencies]
base64 = "0.22"
serde_json = "1.0"
